name: GitHub Pages CI
on:
  push:
    branches:
      - main
    paths:
      - fmt-charts/**
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1 #this will install Node and npm on Ubuntu
    - run: npm install
    - run: npm install -g @angular/cli > /dev/null
    - run: ng build --prod --output-path=docs --base-href="https://petermefrandsen.github.io/Follow-the-token/"
    - name: Publish generated content to GitHub Pages
      uses: tsunematsu21/actions-publish-gh-pages@v1.0.1
      with:
          dir: docs
          branch: gh-pages
          token: ${{ secrets.ACCESS_TOKEN }}